# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OLED add-on
version: "0.0.35"
slug: oled
description: Use OLED screens via i2c
url: "https://github.com/ghhaam/ha-addons/tree/main/oled"
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services: 
  - mqtt:need
init: false
apparmor: false
full_access: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-22
map:
  - config:rw
options:
  message: "Hello world!"
  message_font_size: 40
  message_coordinate_x: 1
  message_coordinate_y: 1
  message_unit: "ppm"
  message_unit_font_size: 18
  message_unit_coordinate_x: 1
  message_unit_coordinate_y: 41
  mqtt_message_lisener: "oled/message"
  display_interface_serial: i2c
  display_interface_port: 1
  display_interface_address: 60
  display_type: ssd1306
  display_rotate: "2"
  display_contrast: 50
schema: 
  message: str
  message_font_size: int
  message_coordinate_x: int
  message_coordinate_y: int
  message_unit: str
  message_unit_font_size: int
  message_unit_coordinate_x: int
  message_unit_coordinate_y: int
  mqtt_message_lisener: str
  display_interface_serial: list(i2c)
  display_interface_port: int
  display_interface_address: int
  display_type: list(sh1106|ssd1306|ssd1309|ssd1325|ssd1331|ws0010)
  display_rotate: list(0|1|2|3)
  display_contrast: int
#image: "ghcr.io/home-assistant/{arch}-addon-example"
